### ISSUE TITLE
Issue with opening model files

### ISSUE THREAD

**Issue by sfikas** [kris314/hwnet#1]
Hi, I am trying to open the model files (t7) that you provide. I have tried the following:
``import torch``
``from torch.utils.serialization import load_lua``
``x = load_lua('gw-model.t7')``
to which I am getting the error:
``T7ReaderException: unknown type id 176816768. The file may be corrupted.``
Same happens for the other model files as well.

I am using Pytorch 0.4 . How can I get around this issue ? Thanks in advance!

**Comment by kris314** [comment]
Hi,

The above model was trained on Pytorch 0.2 and Python 2.7. 
Please load the model using the below command:
checkpoint = torch.load('gw-model.t7')
net = checkpoint['net']

Ref: hwnet/pytorch/hwnet-feat.py from the repository for loading and feature extraction.

Thanks

**Comment by sfikas** [comment]
It works. Thanks!
