### ISSUE TITLE
What is the Ground truth files for different pretrained model.

### ISSUE THREAD

**Issue by mesrh** [kris314/hwnet#4]
In the pre-trained model gw-model and iam-model, the last layer has a dimension of 987 and 8135 respectively, which is the size of the vocabulary.

But the ground truth file size is of only 10k or 90k available. 
Are you taking the subset of these ground truth file? 
Could you please share the exact subset of ground truth file for different pre-trained model.
It will be helpful in fine-tuning the model.

Thanks,

**Comment by kris314** [comment]
Hi,

HWNet was first trained on synthetic data where the vocabulary was 10K. Later for each dataset, it was fine-tuned with the training data of the respective dataset. For IAM the training dataset has a vocabulary (~unique words of 8K) while GW has ~1K.

For fine-tuning, you need to reinitialize the last layer to the size of the vocabulary of your new training set.

**Comment by mesrh** [comment]
Thank you, for your quick response.
